# 트러블 슈팅
<br>

## ⚠️ 문제 해결

<br>

---

<br>
<h3>🔒댓글 기능 경로 지정 오류 </h3>
<br>
-model과 url,views의 작성이 끝나고 프로그램을 실행시켰을 때, 오류코드가 뜨면서 실행이 되지않았습니다.
-해당 문제는 urls.py에서 경로를 수정해 준 후 해결되었습니다.
<br>

```python
# 변경 전
urlpatterns = [
    path('/comment', views.create_comment, name= 'create_comment'),
]

#변경 후
urlpatterns = [
    path('comment/<int:id>/', views.create_comment, name= 'create_comment'),
]
```

<br>

---

<br><br>
<h3>🌁저장된 이미지 파일을 EasyOCR에 활용할 때 에러</h3>
<br>

1. 이미지 경로 주소를 http url로 담아 보내는 경우.
2. `Cobby.image.url` 사용시, 인코딩되어 불러와지는 경우.
3. `/media/.../img.png` 제일 앞에 `/`가 붙어 경로를 못찾는 경우.
  - 다음와 같이 오류를 해결했습니다.
  1. 굳이 다른 url로 보내지 않고, 이미지 파일을 저장하는 url과 view에서 처리했습니다.
  2. 다음 코드와 같이 해결했습니다.
  
  ```python
  from urllib import parse
  ...
  (중략)
  ...
  result_list = reader.readtext(parse.unquote(new_file.image.url[1:]))
  ...
  ```

  - `parse.unquote`를 통해 인코딩된 주소를 본래 문자열로 돌려주었습니다.
  - 문자열을 인덱스 1부터 슬라이싱해주어 `/`를 떼주었습니다.
  
  <br>
  <br>
  
----

<br>

<br>
<h3> ⚠️게시글 검색 과정에서 QuerySet 리스트 형태로 들어오는 정보를 넘겨주지 못하면서 발생한 오류.</h3>

1. 오류 수정 과정에서 발생했던 다른 오류 문구. 

<br>

- **'QuerySet' indices must be integers or slices, not 'str'.**

리스트의 인댁스는 문자열이 아니라 정수여야 한다.

- **'QuerySet' object has no attribute 'id'**


<br>

```python
# 변경 전

 if search :
        post_list = post_list.filter(title__icontains=search)
        
    return render(request, 'post/post_search.html', {'Post_search' : post_list})

# 변경 후

    if search :
        post_list = post_list.filter(name__icontains=search)
        post_id = post_list.values()[0]['id']
    return redirect(f'/makgeolli/{post_id}')

```
<br>
2. 발생 원인 및 해결
QuerySet은 전달받은 모델의 객체 목록으로 아래의 형태로 데이터가 전달이 되는데, 리스트[] 안에, 딕셔너리{} 형태임을 볼 수 있다.
첫 번째로 작성한 코드에서는 어떤 데이터를 넘겨주는지가 불명확했고, 어떤 데이터를 넘겨줄지를 명확하게 지정해주면서 문제를 해결했다.
<br><br>

```terminal

<QuerySet [<Post: [Django Tutorial] Blog 만들기 - 4. 모델>, <Post: [Django Tutorial] Blog 만들기- 5. 데이터베이스>, <Post: [Django Tutorial] Blog 만들기 - 1. 환경설정>, <Post: [Django Tutorial] Blog 만들기 - 2. 프로젝트 시작>, <Post: [Django Tutorial] Blog 만들기 - 3. 앱>]>

```

<br>

---
<br>
<h3>user app 과 signup.html을 열결하는 과정에서 생긴 오류.<h3>
<br>
1. 다른 작업물과 충돌 후 pull을 하였을 때 그 전과 다르게 views.py의 signup 함수가 htmml을 전혀 읽어오지 못하였다.

<br>
pull 했던 파일을 확인해보니 user/templates/signup.html 형식이 아니라
templates/user/signup.html 형식으로 파일이 저장 되어 있었고, <br>
views.py의 signup 함수의 render 경로를 전부 아래와 같이 변경해 주었다.<br>
<br>

```python
    return render(request, 'user/signup.html') #파일 경로에 따라 바뀜.

```
<br>

---
<h3></h3>






<br>

---

<br>
<h3></h3>
<br>

```python

```

<br>


<br><br>

----

<br><br>

### 


```python

```



```django html

```



